"""Add role row

Revision ID: 17e49dae63db
Revises: ef75e91d01ff
Create Date: 2023-04-10 18:48:21.739401

"""
from alembic import op
import sqlalchemy as sa
from app.domain.user.entities.user import RolesDB


# revision identifiers, used by Alembic.
revision = "17e49dae63db"
down_revision = "ef75e91d01ff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("role", RolesDB(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "role")
    # ### end Alembic commands ###
