"""Add talk_id

Revision ID: e28d73d30248
Revises: e4f8b2181c39
Create Date: 2023-04-10 21:24:22.069450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e28d73d30248'
down_revision = 'e4f8b2181c39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('talk_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'talk', ['talk_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'talk_id')
    # ### end Alembic commands ###
